version: "3.9"

services:
  suma:
    build: ./suma
    ports:
      - "8001:8000"
    networks:
      - shape-net

  resta:
    build: ./resta
    ports:
      - "8002:8000"
    networks:
      - shape-net

  ecuacion:
    build: ./ecuacion
    ports:
      - "8003:8000"
    depends_on:
      - suma
      - resta
      - storage
    networks:
      - shape-net

  storage:
    build: ./storage
    ports:
      - "8004:8000"
    depends_on:
      - mysql
    networks:
      - shape-net

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: microservicios_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - shape-net

networks:
  shape-net:
    driver: bridge

volumes:
  db-data:
